# Generated by Django 5.1.3 on 2024-12-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo_Titular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField(null=True)),
                ('estado_juega', models.BooleanField(default=True)),
                ('descripcion', models.TextField(default='ingresar del 1 - 10, como se encuentra/siente el jugador')),
            ],
        ),
        migrations.CreateModel(
            name='Fecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('resultado', models.CharField(default='pts equipo/pts rival', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField(null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('descripcion', models.TextField(default='ej, tipo de juego, habilidades, caracteristicas, condiciones')),
            ],
        ),
    ]
